### ISSUE TITLE
PyODK 0.2.0, Client has no module auth

### ISSUE THREAD

**Issue by lpofredc** [PnX-SI/odk2gn#2]
La version 0.2.0 de PyODK apporte quelques changements, la fonction `auth` n'existe plus dans la classe `Client` et soulève l'erreur suivante:
```
(venv) user:~/gnModules/odk2gn$ synchronize stom --form_id=stom_form --project_id=1
INFO:app:--- Start synchro for module stom ---
WARNING:app:No mapping found for module stom - get the default ODK monitoring template mapping !  
WARNING:app:The following specific columns are missing from ODK form :
-habitat_input
URL BIS################## projects/1/forms/stom_form/submissions/uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0/attachments/None
WARNING:app:Image not found for submission uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0
URL BIS################## projects/1/forms/stom_form/submissions/uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0/attachments/None
WARNING:app:Image not found for submission uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0
URL BIS################## projects/1/forms/stom_form/submissions/uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0/attachments/None
WARNING:app:Image not found for submission uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0
URL BIS################## projects/1/forms/stom_form/submissions/uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0/attachments/None
WARNING:app:Image not found for submission uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0
URL BIS################## projects/1/forms/stom_form/submissions/uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0/attachments/None
WARNING:app:Image not found for submission uuid:6f2d4215-262b-4e88-a987-0161ecfe87f0
Traceback (most recent call last):
  File "/home/gnadmin/geonature/backend/venv/bin/synchronize", line 11, in <module>
    load_entry_point('odk2gn', 'console_scripts', 'synchronize')()
  File "/home/gnadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gnadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/gnadmin/gnModules/odk2gn/odk2gn/main.py", line 179, in synchronize
    update_review_state(project_id, form_id, sub["__id"], "approved")
  File "/home/gnadmin/gnModules/odk2gn/odk2gn/odk_api.py", line 79, in update_review_state
    token = client.auth.get_token(
AttributeError: 'Client' object has no attribute 'auth'
```

**Comment by TheoLechemia** [comment]
Fait
