### ISSUE TITLE
No such command 'odk2gn'

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/odk2gn#31]
GN : 2.14.2
ODK2GN : 1.0.0

Bonjour à tous, 
je souhaite parvenir à utiliser ce super module, mais pour une raison que j'ignore, je ne parviens pas à accéder aux commandes du module ce qui me pose question..
Ci-dessous les commandes tester après avoir suivi la doc d'installation.

Commande testée :
``` bash
> source geonature/backend/venv/bin/activate
> geonature odk2gn --help
Error: No such command 'odk2gn'.
```
``` bash
> source geonature/backend/venv/bin/activate
> odk2gn --help
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/odk2gn", line 5, in <module>
    from odk2gn.main import odk2gn
ModuleNotFoundError: No module named 'odk2gn.main'
```
Dans la dernière release, Python > 3.10 est mentionné. 
La version de python3 installé sur la machine est python3==3.10.12. Est-ce bon ou faut-il absolument python3.11 ?

La commande que j'ai testé `odk2gn --help` me laisse pensé que l'installation de la librairie odk2gn n'est pas bonne. Il n'existe pas de fichier `main.py` dans le dossier python odk2gn. Est-il manquant ?

**Comment by lpojgc** [comment]
Bonjour,
On constate la même chose sur notre instance depuis la montée en version vers la 2.14.2, les commandes ODK ne sont plus trouvées... Alors que ça fonctionnait en 2.13.xx
Pour le moment nous sommes secs de notre côté...

**Comment by TheoLechemia** [comment]
Salut,
que renvoie la commande `pip show odk2gn` dans le virtualenv de GeoNature ?
Si vous avez un `WARNING: Package(s) not found: odk2gn`, vous pouvez tentez de réinstaller la lib : 
` 
# toujours dans le venv geonature
cd odk2gn
pip install -e .
`
Normalement le venv n'est pas supprimé lors des monté de version du coup je sais pas pourquoi vous n'avez plus la lib ..

**Comment by cen-cgeier** [comment]
Salut Theo, `pip show odk2gn` renvoie 
``` py
Name: odk2gn
Version: 1.0.0
Summary: GeoNature-monitoring ODK project
Home-page: 
Author: 
Author-email: 
License: 
Location: /home/geonatureadmin/geonature/backend/venv/lib/python3.10/site-packages
Editable project location: /home/geonatureadmin/odk2gn
Requires: colorlog, flatdict, pyodk
Required-by: 
```

**Comment by TheoLechemia** [comment]
Ok,
est quand tu lance juste la commande `geonature`, est ce que tu vois passer des erreur lié à ODK2GN : `Unable to load module ODK2GN, skipping…`

**Comment by cen-cgeier** [comment]
Non rien qui se rapporte à ODK2GN

**Comment by TheoLechemia** [comment]
Du coup est ce que tu peux essayer de réinstaller le module : 
`geonature install-gn-module <chemin-vers-odk2gn> --build=false --upgrade-db=false`

**Comment by lpojgc** [comment]
De notre côté après réinstallation du module, ça fonctionne, merci :-)
Colas pour info on est une sur version 3.9 de python

**Comment by TheoLechemia** [comment]
Je sèche un peu Colas, désolé.
Je reproduit pas non plus en local en python 3.10 ni sur notre serveur de test en 3.11 ..

**Comment by cen-cgeier** [comment]
Merci du retour, merci Théo du temps passé.
Je vais creuser la question de mon côté et vous tiens informé quand j'en découvre un peu plus ! :pick:

**Comment by cen-cgeier** [comment]
Bonjour à tous,

voici quelques nouvelles. J'ai pu trouver 2 points de blocage sur mon instance dans l'import de la librairie odk2gn, dont 1 qui semble responsable de l'absence de la commande `geonature odk2gn`:

**- Point bloquant  :**   
Dans le fichier `admin.py` la class `Markup` est importée depuis la librairie `flask` et voici le retour de la commande d'import.
``` py 
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
App: geonature
Instance: /home/geonatureadmin/geonature/backend/instance
>>> from flask import Markup
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'Markup' from 'flask' (/home/geonatureadmin/geonature/backend/venv/lib/python3.10/site-packages/flask/__init__.py)
```
En parcourant d'autres modules tel que le module `import`, la class `Markup` est importée de la manière suivante 
``` py
from markupsafe import Markup
```
Modifier l'import de `Markup` m'a permis d'obtenir la commande `geonature odk2gn`.

**- Autre point :** 
Dans le fichier `gn2_utils.py`, la fonction `asShape` est importée depuis `shapely.geometry` mais il semble que cette fonction est disparue de la librairie Shapely depuis sa version 2.0 (https://shapely.readthedocs.io/en/stable/migration.html#other-deprecated-functionality)

Qu'en pensez-vous ?
``` py
>>> from shapely.geometry import asShape
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'asShape' from 'shapely.geometry' (/home/geonatureadmin/geonature/backend/venv/lib/python3.10/site-packages/shapely/geometry/__init__.py)
```

**Comment by cen-cgeier** [comment]
Tout semble déjà avoir été corrigée par @TheoLechemia  2eab41251998dc0fbadb2728bb5c2972abe97989,
notamment avec la suppression de l'import de flask (l.1 dans le fichier admin.py).
C'est correction sont font partie de la branche `feat/gn_215` mais il semble qu'elles soient également nécessaire à GN==2.14.2

**Comment by camillemonchicourt** [comment]
Oui oui on n'a pas eu le temps de développer et publier une version compatible GN 2.13 et GN 2.14 avec les systèmes de permissions disponibles notamment, mais potentiellement d'autres choses.

Théo a cependant préparé une version compatible 2.15 dans cette PR.

**Comment by camillemonchicourt** [comment]
La version 2.15 de GeoNature et la version 1.0.0 de Monitoring sont sortis.
Il faudrait donc merger la PR https://github.com/PnX-SI/odk2gn/pull/32.
Mais il serait utile de faire quelques tests avant si certains en ont l'occasion.
